'use client'

import Image from 'next/image'
import { useState } from 'react'
import { ArrowUpRight, Compass, Menu, MoveRight, Phone, Sparkles, X } from 'lucide-react'

const services = [
  ['01', 'Home harmony', 'Practical guidance for buying, renting, or redesigning a home.'],
  ['02', 'Workplace flow', 'Spatial advice for focus, culture, and better work.'],
  ['03', 'Developer advisory', 'A considered perspective from concept through handover.'],
]

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false)
  return <main className="min-h-screen overflow-hidden bg-[#fcfaf6] text-[#263c35]">
    <header className="border-b border-[#263c35]/10 bg-[#fcfaf6]/90 backdrop-blur-md"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-10"><a href="#home" className="flex items-center gap-3" aria-label="Kavach Consultancy home"><span className="grid size-10 place-items-center rounded-full bg-[#f4dfd3] text-[#a8553f]"><Compass className="size-5" /></span><span className="font-serif text-xl">Kavach<span className="text-[#a8553f]">.</span></span></a><nav className="hidden gap-8 text-sm lg:flex" aria-label="Primary navigation"><a href="#about">About</a><a href="#services">Services</a><a href="#journal">Journal</a><a href="#contact">Contact</a></nav><a href="#book" className="hidden rounded-full bg-[#263c35] px-5 py-3 text-sm font-medium text-[#fcfaf6] lg:block">Book a consultation <ArrowUpRight className="ml-2 inline size-4" /></a><button className="rounded-full border border-[#263c35]/15 p-2 lg:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? 'Close menu' : 'Open menu'} aria-expanded={menuOpen}>{menuOpen ? <X /> : <Menu />}</button></div>{menuOpen && <nav className="flex flex-col gap-5 border-t border-[#263c35]/10 px-5 py-6 text-sm lg:hidden"><a href="#about" onClick={() => setMenuOpen(false)}>About</a><a href="#services" onClick={() => setMenuOpen(false)}>Services</a><a href="#journal" onClick={() => setMenuOpen(false)}>Journal</a><a href="#contact" onClick={() => setMenuOpen(false)}>Contact</a></nav>}</header>
    <section id="home" className="mx-auto grid max-w-7xl gap-14 px-5 py-16 lg:grid-cols-[1.03fr_.97fr] lg:items-center lg:px-10 lg:py-24"><div><p className="mb-7 text-xs font-medium uppercase tracking-[.2em] text-[#a8553f]">Spatial advisory, rooted in Vastu</p><h1 className="font-serif text-5xl leading-[.98] tracking-[-.045em] sm:text-6xl lg:text-[6.7rem]">Spaces that<br /><em className="font-normal text-[#a8553f]">feel like home.</em></h1><p className="mt-8 max-w-md leading-7 text-[#263c35]/70">Modern Vastu advisory for homes, workplaces and developments across Dubai — practical, personal, and grounded in how you want to live.</p><div className="mt-9 flex flex-wrap gap-4"><a href="#book" className="rounded-full bg-[#a8553f] px-6 py-3.5 text-sm font-medium text-white">Start a conversation <MoveRight className="ml-2 inline size-4" /></a><a href="#services" className="rounded-full border border-[#263c35]/20 px-6 py-3.5 text-sm font-medium">Explore services</a></div><p className="mt-12 text-sm text-[#263c35]/65">Independent advisory for homes across the UAE</p></div><div className="relative mx-auto w-full max-w-[550px]"><div className="relative aspect-[.87] overflow-hidden rounded-[13rem] rounded-br-[3rem] rounded-tl-[3rem] bg-[#dfe9df]"><Image src="/images/kavach-hero.png" alt="Sunlit interior with a rounded doorway and indoor greenery" fill sizes="(max-width: 1024px) 100vw, 550px" className="object-cover" priority /></div><p className="mt-4 text-right font-serif text-sm italic text-[#263c35]/60">Dubai · UAE</p></div></section>
    <section id="about" className="mx-auto grid max-w-7xl gap-12 px-5 py-24 lg:grid-cols-[.85fr_1.15fr] lg:px-10"><div><p className="text-xs uppercase tracking-[.2em] text-[#a8553f]">A different way to look at space</p><h2 className="mt-5 font-serif text-4xl sm:text-5xl">Ancient wisdom.<br /><em className="font-normal text-[#a8553f]">Clear-eyed advice.</em></h2></div><div className="max-w-xl"><p className="text-xl leading-8 text-[#263c35]/80">Vastu is not about fear or rigid rules. It is a thoughtful way to understand how light, movement, orientation and intention shape the way a space feels.</p><p className="mt-6 leading-7 text-[#263c35]/65">Every recommendation is practical, considered, and tailored to the way you and your people actually live.</p></div></section>
    <section id="services" className="bg-[#dfe9df] px-5 py-24 lg:px-10"><div className="mx-auto max-w-7xl"><p className="text-xs uppercase tracking-[.2em] text-[#a8553f]">How we help</p><h2 className="mt-4 font-serif text-4xl sm:text-5xl">Advice for the spaces<br /><em className="font-normal text-[#a8553f]">that matter most.</em></h2><div className="mt-12 grid gap-4 md:grid-cols-3">{services.map(([number, title, description], index) => <article key={number} className={`flex min-h-[260px] flex-col justify-between rounded-[2rem] p-7 ${index === 1 ? 'bg-[#f4dfd3]' : index === 2 ? 'bg-[#eee4cf]' : 'bg-[#e8f0e7]'}`}><span className="text-sm text-[#263c35]/50">{number}</span><div><h3 className="font-serif text-3xl">{title}</h3><p className="mt-3 text-sm leading-6 text-[#263c35]/70">{description}</p></div></article>)}</div></div></section>
    <section id="journal" className="bg-[#f4dfd3] px-5 py-24 lg:px-10"><div className="mx-auto max-w-7xl"><p className="text-xs uppercase tracking-[.2em] text-[#a8553f]">From the journal</p><h2 className="mt-4 font-serif text-4xl">A little perspective.</h2><div className="mt-10 grid gap-4 md:grid-cols-3">{['What Vastu is — and what it is not', 'Choosing a home that feels right', 'The quiet power of a well-oriented workplace'].map((title, index) => <article key={title} className="rounded-[1.5rem] bg-[#eee4cf] p-7"><p className="text-xs uppercase tracking-[.15em] text-[#a8553f]">Journal 0{index + 1}</p><h3 className="mt-12 font-serif text-2xl">{title}</h3></article>)}</div></div></section>
    <section id="book" className="mx-auto grid max-w-7xl gap-12 px-5 py-24 lg:grid-cols-[.8fr_1.2fr] lg:px-10"><div><p className="text-xs uppercase tracking-[.2em] text-[#a8553f]">Your next step</p><h2 className="mt-5 font-serif text-5xl">Let&apos;s make<br /><em className="font-normal text-[#a8553f]">space for good.</em></h2><p className="mt-7 max-w-sm leading-7 text-[#263c35]/65">Send an enquiry and your email client will open with the details ready to send.</p><div className="mt-10 flex flex-col gap-4 text-sm"><a href="tel:+971501234567"><Phone className="mr-3 inline size-4 text-[#a8553f]" />+971 50 123 4567 <span className="text-xs text-[#263c35]/50">(placeholder)</span></a><a href="mailto:hello@kavachconsultancy.com"><Sparkles className="mr-3 inline size-4 text-[#a8553f]" />hello@kavachconsultancy.com <span className="text-xs text-[#263c35]/50">(placeholder)</span></a></div></div><form action="mailto:hello@kavachconsultancy.com" method="post" encType="text/plain" className="flex flex-col gap-5 rounded-[2rem] bg-[#f3eee6] p-6 sm:p-10"><label className="flex flex-col gap-2 text-sm">Your name<input required name="name" className="rounded-xl border border-[#263c35]/15 bg-[#fcfaf6] px-4 py-3" /></label><label className="flex flex-col gap-2 text-sm">Email address<input required name="email" type="email" className="rounded-xl border border-[#263c35]/15 bg-[#fcfaf6] px-4 py-3" /></label><label className="flex flex-col gap-2 text-sm">How can we help?<textarea required name="message" rows={5} className="rounded-xl border border-[#263c35]/15 bg-[#fcfaf6] px-4 py-3" /></label><button type="submit" className="rounded-full bg-[#a8553f] px-6 py-3.5 text-sm font-medium text-white">Open email enquiry <ArrowUpRight className="ml-2 inline size-4" /></button></form></section>
    <footer id="contact" className="bg-[#263c35] px-5 py-12 text-[#fcfaf6] lg:px-10"><div className="mx-auto max-w-7xl"><p className="font-serif text-2xl">Kavach.</p><p className="mt-3 text-sm text-white/60">Spatial advisory for more intentional living and working.</p><p className="mt-10 border-t border-white/10 pt-5 text-xs text-white/40">© 2026 Kavach Consultancy · Dubai, UAE</p></div></footer>
  </main>
}
