'use client'

import Image from 'next/image'
import Link from 'next/link'
import { ArrowUpRight } from 'lucide-react'
import { track } from '@vercel/analytics'
import { useLanguage } from '@/components/language'
import { FounderStrip } from '@/components/founder'
import { gallery, services } from '@/components/site-data'
import { Eyebrow, Footer, Header, btn } from '@/components/site-shell'

function CompassRose() {
  return <svg viewBox="0 0 120 120" fill="none" className="size-24 text-[#74512f] sm:size-32" aria-hidden="true">
    <circle cx="60" cy="60" r="43" stroke="currentColor" strokeOpacity=".4" />
    <circle cx="60" cy="60" r="4" fill="currentColor" />
    <path d="M60 9v18m0 66v18M9 60h18m66 0h18M60 30l8 22-8 8-8-8 8-22Zm0 60-8-22 8-8 8 8-8 22ZM30 60l22-8 8 8-8 8-22-8Zm60 0-22 8-8-8 8-8 22 8Z" stroke="currentColor" strokeLinejoin="round" />
    <text x="60" y="8" textAnchor="middle" className="fill-current font-sans text-[8px]">N</text>
    <text x="60" y="119" textAnchor="middle" className="fill-current font-sans text-[8px]">S</text>
    <text x="8" y="63" textAnchor="middle" className="fill-current font-sans text-[8px]">W</text>
    <text x="112" y="63" textAnchor="middle" className="fill-current font-sans text-[8px]">E</text>
  </svg>
}

export function HomePage() { const { t } = useLanguage(); return <><Header overlay /><main>
  <section className="relative h-[88svh] min-h-[560px] max-h-[900px] overflow-hidden bg-[#9fb6cf]"><Image src="/images/hero-villa.jpg" alt={t('Light-filled modern villa with a reflecting pool under a clear sky')} fill sizes="100vw" className="image-drift object-cover object-[center_70%]" priority /><div className="absolute inset-0 bg-gradient-to-b from-[#7f9cbb]/50 via-[#1e0a11]/15 to-[#1e0a11]/90" /><p aria-hidden className="pointer-events-none absolute inset-x-0 top-[14vh] select-none text-center font-sans text-[21vw] font-medium leading-none tracking-[.02em] lg:top-[12vh]"><span className="bg-gradient-to-b from-white via-white/85 to-white/0 bg-clip-text text-transparent">KAVACH</span></p><div className="absolute inset-x-0 bottom-0 z-10 mx-auto grid max-w-7xl gap-8 px-5 pb-12 text-white lg:grid-cols-[1.4fr_1fr] lg:items-end lg:px-10 lg:pb-16"><div><Eyebrow light>Beyond the floor plan</Eyebrow><h1 className="mt-5 max-w-3xl font-serif text-5xl font-light leading-[.98] sm:text-7xl">{t('Feel the fit')} <em className="text-[#d9bf9a]">{t('before you commit.')}</em></h1></div><div className="hero-copy border-l border-white/25 pl-6"><p className="text-sm leading-6 text-white/90">{t('Listings show rooms, not how daylight, circulation and orientation shape daily life. Kavach helps you assess those details before you buy, rent or build.')}</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/bookings" onClick={() => track('Consultation CTA Clicked', { location: 'home_hero' })} className={`${btn} bg-[#74512f] text-white hover:bg-[#8d6539]`}>{t('Start a conversation')} <ArrowUpRight className="size-4" /></Link><Link href="/services" className={`${btn} border border-white/50 hover:bg-white hover:text-[#2a1b1f]`}>{t('Our services')}</Link></div></div></div></section>
  <section className="mx-auto grid max-w-7xl gap-8 px-5 py-16 md:grid-cols-[1fr_auto_1.45fr] md:items-center lg:px-10"><div><Eyebrow>{t('A quick first look')}</Eyebrow><h2 className="mt-5 font-serif text-4xl font-light sm:text-5xl">{t('Quick Vastu checker')}</h2><p className="mt-4 max-w-md leading-7 text-[#2a1b1f]/70">{t('Choose your space for a few useful starting points.')}</p></div><CompassRose /><div className="grid gap-3 sm:grid-cols-3">{([{label:'Home',value:'Home'},{label:'Workplace',value:'Workplace'},{label:'Development project',value:'Development'}] as const).map(({label,value},i)=><Link key={value} href={`/vastu-checker?type=${value}`} className="group flex min-h-[88px] items-center justify-between border-y border-[#2a1b1f]/20 px-4 py-4 transition-colors hover:bg-[#ebe3d8] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#74512f]"><span><span className="block text-[10px] tracking-[.2em] text-[#74512f]">0{i+1}</span><span className="mt-1 block font-serif text-lg">{t(label)}</span></span><ArrowUpRight className="size-4 shrink-0 text-[#74512f] transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></Link>)}</div></section>
  <section className="mx-auto grid max-w-7xl gap-14 px-5 py-28 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:gap-24 lg:px-10"><div className="relative mx-auto w-full max-w-[460px]"><div className="relative aspect-[.8] overflow-hidden rounded-t-full"><Image src="/images/kavach-hero.png" alt={t('Sunlit interior with a rounded doorway and indoor greenery')} fill sizes="(max-width: 1024px) 100vw, 460px" className="object-cover" /></div><p className="mt-4 text-[11px] uppercase tracking-[.22em] text-[#2a1b1f]/70">{t('A considered approach to every space')}</p></div><div><Eyebrow>Our approach</Eyebrow><h2 className="mt-6 font-serif text-5xl font-light leading-[1.05] sm:text-6xl">{t('Light, flow and orientation, read with care.')}</h2><p className="mt-8 max-w-md leading-8 text-[#2a1b1f]/70">{t('Founded by Vedang Joshi, Kavach looks at how a space is lived in: where the morning light lands, how people move, and what each room is asked to do. Recommendations are practical, considered, and shaped around your priorities.')}</p><Link href="/about" className="mt-8 inline-block text-[11px] uppercase tracking-[.22em] text-[#74512f] underline underline-offset-8">{t('Meet your advisor')}</Link></div></section>
  <section className="bg-[#ebe3d8] px-5 py-28 lg:px-10"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-6 border-b border-[#2a1b1f]/15 pb-10 md:flex-row md:items-end"><div><Eyebrow>How we help</Eyebrow><h2 className="mt-6 font-serif text-5xl font-light sm:text-6xl">{t('Advice for the spaces that matter.')}</h2></div><Link href="/services" className="text-[11px] uppercase tracking-[.22em] text-[#74512f] underline underline-offset-8">{t('All services')}</Link></div><div className="mt-12 grid gap-10 md:grid-cols-3 md:gap-8">{services.map(([title, description, src, alt], i) => <Link href={`/services#${title.toLowerCase().replaceAll(' ','-')}`} key={title} className="group block"><div className="relative aspect-[4/5] overflow-hidden"><Image src={src} alt={t(alt)} fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover transition-transform duration-[1.2s] group-hover:scale-[1.04]" /></div><div className="mt-6 flex gap-5"><span className="font-serif text-lg italic text-[#74512f]">0{i+1}</span><div><h3 className="font-serif text-3xl">{t(title)}</h3><p className="mt-2 text-sm leading-6 text-[#2a1b1f]/65">{t(description)}</p></div></div></Link>)}</div></div></section>
  <section className="px-5 py-24 lg:px-10"><div className="mx-auto max-w-7xl"><Eyebrow>How a review works</Eyebrow><h2 className="mt-6 max-w-3xl font-serif text-4xl font-light leading-tight sm:text-5xl">{t('From first look to a clearer next step.')}</h2><div className="mt-12 grid gap-8 md:grid-cols-3 md:gap-10">{[['01','Tell us what matters','Share your plan, priorities and where you are in the process.'],['02','Review how the space works','Consider orientation, daylight, circulation and the way each room will be used.'],['03','Leave with practical next steps','Discuss practical points to explore before you buy, renovate or build.']].map(([number,title,description])=><article key={number} className="border-t border-[#2a1b1f]/15 pt-6"><p className="font-serif text-xl italic text-[#74512f]">{number}</p><h3 className="mt-4 font-serif text-2xl">{t(title)}</h3><p className="mt-3 max-w-sm text-sm leading-7 text-[#2a1b1f]/70">{t(description)}</p></article>)}</div></div></section>
  
  <FounderStrip />
  <section className="mx-auto max-w-7xl px-5 py-28 lg:px-10"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><Eyebrow>Selected spaces</Eyebrow><h2 className="mt-6 font-serif text-5xl font-light sm:text-6xl">{t('Calm, considered, lived in.')}</h2></div><Link href="/blogs" className="text-[11px] uppercase tracking-[.22em] text-[#74512f] underline underline-offset-8">{t('Read the journal')}</Link></div><div className="mt-14 grid auto-rows-[260px] gap-x-4 gap-y-12 md:grid-cols-4">{gallery.map(([src, alt, caption, place, span]) => <figure key={src} className={`group flex flex-col ${span}`}><div className="relative min-h-0 flex-1 overflow-hidden"><Image src={src} alt={t(alt)} fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover transition-transform duration-[1.2s] group-hover:scale-[1.04]" /></div><figcaption className="mt-3 flex justify-between gap-4 text-xs"><span className="font-serif text-base italic">{t(caption)}</span><span className="uppercase tracking-[.18em] text-[#2a1b1f]/70">{t(place)}</span></figcaption></figure>)}</div></section>
  <section className="relative h-[80svh] min-h-[480px] overflow-hidden"><Image src="/images/dubai-skyline.jpg" alt={t('Dubai skyline at sunrise')} fill sizes="100vw" className="image-drift object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#1e0a11]/90 via-[#1e0a11]/25 to-transparent" /><div className="absolute inset-x-0 bottom-0 mx-auto max-w-7xl px-5 pb-14 text-white lg:px-10"><Eyebrow light>Based in Dubai</Eyebrow><h2 className="mt-6 max-w-3xl font-serif text-5xl font-light leading-[1.02] sm:text-7xl">{t('Ready when you are. Let’s begin.')}</h2><div className="mt-9 flex flex-wrap gap-3"><Link href="/contact" className={`${btn} border border-white/50 hover:bg-white hover:text-[#2a1b1f]`}>{t('Contact us')}</Link></div></div></section>
</main><Footer /></> }

