'use client'

import Image from 'next/image'
import Link from 'next/link'
import { FormEvent, useState } from 'react'
import { ArrowUpRight, Compass, Menu, MoveRight, Phone, Sparkles, X } from 'lucide-react'

const nav = [['Home','/'],['About','/about'],['Services','/services'],['Journal','/blogs'],['Contact','/contact'],['Bookings','/bookings']] as const
const services = [['Home harmony','Guidance for buying, renting, or redesigning a home.'],['Workplace flow','Spatial advice for focus, culture, and better work.'],['Developer advisory','A considered perspective from concept through handover.']] as const

export function Header() {
  const [open, setOpen] = useState(false)
  return <header className="border-b border-[#263c35]/10 bg-[#fcfaf6]/90 backdrop-blur-md"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-10"><Link href="/" className="flex items-center gap-3" aria-label="Kavach home"><span className="grid size-10 place-items-center rounded-full bg-[#f4dfd3] text-[#a8553f]"><Compass className="size-5" /></span><span className="font-serif text-xl">Kavach<span className="text-[#a8553f]">.</span></span></Link><nav className="hidden gap-8 text-sm lg:flex" aria-label="Primary navigation">{nav.map(([label, href]) => <Link key={href} href={href}>{label}</Link>)}</nav><Link href="/bookings" className="hidden rounded-full bg-[#263c35] px-5 py-3 text-sm font-medium text-[#fcfaf6] lg:block">Book a consultation <ArrowUpRight className="ml-2 inline size-4" /></Link><button className="rounded-full border border-[#263c35]/15 p-2 lg:hidden" onClick={() => setOpen(!open)} aria-label={open ? 'Close menu' : 'Open menu'}>{open ? <X /> : <Menu />}</button></div>{open && <nav className="flex flex-col gap-5 border-t border-[#263c35]/10 px-5 py-6 text-sm lg:hidden">{nav.map(([label, href]) => <Link onClick={() => setOpen(false)} key={href} href={href}>{label}</Link>)}</nav>}</header>
}

export function Footer() { return <footer className="bg-[#263c35] px-5 py-12 text-[#fcfaf6] lg:px-10"><div className="mx-auto max-w-7xl"><p className="font-serif text-2xl">Kavach.</p><p className="mt-3 text-sm text-white/60">Spatial advisory for more intentional living and working.</p><p className="mt-10 border-t border-white/10 pt-5 text-xs text-white/40">© 2026 Kavach Consultancy · Dubai, UAE</p></div></footer> }

export function HomePage() { return <><Header /><main><section className="mx-auto grid max-w-7xl gap-14 px-5 py-16 lg:grid-cols-[1.03fr_.97fr] lg:items-center lg:px-10 lg:py-24"><div><p className="mb-7 text-xs font-medium uppercase tracking-[.2em] text-[#a8553f]">Spatial advisory, rooted in Vastu</p><h1 className="font-serif text-5xl leading-[.98] tracking-[-.045em] sm:text-6xl lg:text-[6.7rem]">Spaces that<br /><em className="font-normal text-[#a8553f]">feel like home.</em></h1><p className="mt-8 max-w-md leading-7 text-[#263c35]/70">Modern Vastu advisory for homes, workplaces and developments across Dubai — practical, personal, and grounded in how you want to live.</p><div className="mt-9 flex flex-wrap gap-4"><Link href="/bookings" className="rounded-full bg-[#a8553f] px-6 py-3.5 text-sm font-medium text-white">Start a conversation <MoveRight className="ml-2 inline size-4" /></Link><Link href="/services" className="rounded-full border border-[#263c35]/20 px-6 py-3.5 text-sm font-medium">Explore services</Link></div></div><div className="relative mx-auto w-full max-w-[550px]"><div className="relative aspect-[.87] overflow-hidden rounded-[13rem] rounded-br-[3rem] rounded-tl-[3rem] bg-[#dfe9df]"><Image src="/images/kavach-hero.png" alt="Sunlit interior with a rounded doorway and indoor greenery" fill sizes="(max-width: 1024px) 100vw, 550px" className="object-cover" priority /></div><p className="mt-4 text-right font-serif text-sm italic text-[#263c35]/60">Dubai · UAE</p></div></section><section className="bg-[#dfe9df] px-5 py-24 lg:px-10"><div className="mx-auto max-w-7xl"><p className="text-xs uppercase tracking-[.2em] text-[#a8553f]">How we help</p><h2 className="mt-4 font-serif text-4xl sm:text-5xl">Advice for spaces that matter most.</h2><div className="mt-12 grid gap-4 md:grid-cols-3">{services.map(([title, description], i) => <Link href={`/services#${title.toLowerCase().replaceAll(' ','-')}`} key={title} className={`flex min-h-[260px] flex-col justify-between rounded-[2rem] p-7 ${i===1?'bg-[#f4dfd3]':i===2?'bg-[#eee4cf]':'bg-[#e8f0e7]'}`}><span className="text-sm text-[#263c35]/50">0{i+1}</span><div><h3 className="font-serif text-3xl">{title}</h3><p className="mt-3 text-sm leading-6 text-[#263c35]/70">{description}</p></div></Link>)}</div></div></section></main><Footer /></> }

export function StandardPage({title, eyebrow, children}: {title:string; eyebrow:string; children:React.ReactNode}) { return <><Header /><main className="mx-auto max-w-7xl px-5 py-20 lg:px-10 lg:py-28"><p className="text-xs uppercase tracking-[.2em] text-[#a8553f]">{eyebrow}</p><h1 className="mt-5 max-w-3xl font-serif text-5xl leading-tight sm:text-7xl">{title}</h1><div className="mt-14">{children}</div></main><Footer /></> }

export function BookingForm() { const [status, setStatus] = useState(''); async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = e.currentTarget; const res = await fetch('/api/bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(form)))}); setStatus(res.ok ? 'Thanks — your booking enquiry has been received.' : 'Something went wrong. Please try again.'); if(res.ok) form.reset() } return <form onSubmit={submit} className="flex max-w-2xl flex-col gap-5 rounded-[2rem] bg-[#f3eee6] p-6 sm:p-10"><label className="flex flex-col gap-2 text-sm">Your name<input required name="name" className="rounded-xl border border-[#263c35]/15 bg-[#fcfaf6] px-4 py-3" /></label><label className="flex flex-col gap-2 text-sm">Email address<input required name="email" type="email" className="rounded-xl border border-[#263c35]/15 bg-[#fcfaf6] px-4 py-3" /></label><label className="flex flex-col gap-2 text-sm">Phone number<input required name="phone" type="tel" className="rounded-xl border border-[#263c35]/15 bg-[#fcfaf6] px-4 py-3" /></label><label className="flex flex-col gap-2 text-sm">Preferred date<input required name="date" type="date" className="rounded-xl border border-[#263c35]/15 bg-[#fcfaf6] px-4 py-3" /></label><label className="flex flex-col gap-2 text-sm">Property type<select required name="propertyType" className="rounded-xl border border-[#263c35]/15 bg-[#fcfaf6] px-4 py-3"><option value="">Select one</option><option>Home</option><option>Workplace</option><option>Development</option></select></label><label className="flex flex-col gap-2 text-sm">How can we help?<textarea required name="message" rows={5} className="rounded-xl border border-[#263c35]/15 bg-[#fcfaf6] px-4 py-3" /></label><button className="rounded-full bg-[#a8553f] px-6 py-3.5 text-sm font-medium text-white">Submit booking enquiry <ArrowUpRight className="ml-2 inline size-4" /></button>{status && <p role="status" className="text-sm text-[#263c35]">{status}</p>}</form> }

export { Phone, Sparkles }

export const ServiceCards = () => <div className="grid gap-4 md:grid-cols-3">{services.map(([title, description], i) => <article id={title.toLowerCase().replaceAll(' ','-')} key={title} className={`rounded-[2rem] p-7 ${i===1?'bg-[#f4dfd3]':i===2?'bg-[#eee4cf]':'bg-[#e8f0e7]'}`}><h2 className="font-serif text-3xl">{title}</h2><p className="mt-4 leading-7 text-[#263c35]/70">{description}</p><p className="mt-8 text-sm text-[#a8553f]">Tailored consultation →</p></article>)}</div>

export const Booking = () => <StandardPage eyebrow="Your next step" title="Let&apos;s make space for good."><p className="mb-10 max-w-xl leading-7 text-[#263c35]/70">Tell us a little about your space and preferred timing. We will review your enquiry and respond with next steps.</p><BookingForm /></StandardPage>
export const Contact = () => <StandardPage eyebrow="Get in touch" title="A thoughtful conversation starts here."><div className="flex flex-col gap-5 text-lg"><a href="tel:+971501234567"><Phone className="mr-3 inline text-[#a8553f]" />+971 50 123 4567 <span className="text-sm text-[#263c35]/50">(placeholder)</span></a><a href="mailto:hello@kavachconsultancy.com"><Sparkles className="mr-3 inline text-[#a8553f]" />hello@kavachconsultancy.com <span className="text-sm text-[#263c35]/50">(placeholder)</span></a></div></StandardPage>
export const Blogs = () => <StandardPage eyebrow="From the journal" title="A little perspective."><div className="grid gap-4 md:grid-cols-3">{[['What Vastu is — and what it is not','A grounded introduction to Vastu, separating practical spatial guidance from superstition and rigid rules.'],['Choosing a home that feels right','A simple lens for noticing light, flow, orientation, and the everyday feeling of a potential home.'],['The quiet power of a well-oriented workplace','How thoughtful planning can support focus, collaboration, and a calmer rhythm at work.']].map(([title, preview],i)=><article key={title} tabIndex={0} className="group relative cursor-help rounded-[1.5rem] bg-[#f4dfd3] p-7 outline-none transition-shadow duration-300 hover:shadow-[0_18px_45px_rgba(38,60,53,.16)] focus-visible:ring-2 focus-visible:ring-[#a8553f] focus-visible:ring-offset-4"><p className="text-xs uppercase tracking-[.15em] text-[#a8553f]">Article 0{i+1}</p><h2 className="mt-12 font-serif text-2xl">{title}</h2><p className="mt-6 text-sm leading-6 text-[#263c35]/70">Practical notes for creating spaces that support the way you live and work.</p><div role="tooltip" className="pointer-events-none absolute inset-x-4 bottom-4 translate-y-3 rounded-2xl bg-[#263c35] p-4 text-sm leading-6 text-[#fcfaf6] opacity-0 shadow-xl transition-all duration-300 group-hover:translate-y-0 group-hover:opacity-100 group-focus:translate-y-0 group-focus:opacity-100">{preview}</div></article>)}</div></StandardPage>
export const About = () => <StandardPage eyebrow="A different way to look at space" title="Ancient wisdom. Clear-eyed advice."><div className="max-w-2xl text-xl leading-8 text-[#263c35]/80">Vastu is not about fear or rigid rules. It is a thoughtful way to understand how light, movement, orientation and intention shape the way a space feels.<p className="mt-6 text-base leading-7 text-[#263c35]/65">Every recommendation is practical, considered, and tailored to the way you and your people actually live.</p></div></StandardPage>
export const Services = () => <StandardPage eyebrow="How we help" title="Advice for the spaces that matter most."><ServiceCards /></StandardPage>
