'use client'

import Image from 'next/image'
import Link from 'next/link'
import { FormEvent, useState } from 'react'
import { ArrowUpRight, Mail, MapPin, Menu, MessageCircle, Phone, Sparkles, X, type LucideIcon } from 'lucide-react'

// Contact sits last so every navigation path ends with a way to reach us.
const nav = [['Home','/'],['About','/about'],['Services','/services'],['Journal','/blogs'],['Bookings','/bookings'],['Contact','/contact']] as const
const services = [['Home harmony','Guidance for buying, renting, or redesigning a home.','/images/bright-living.jpg','Bright open-plan living room with soft sofas'],['Workplace flow','Spatial advice for focus, culture, and better work.','/images/workplace.jpg','Calm modern office corridor with natural tones'],['Developer advisory','A considered perspective from concept through handover.','/images/timber-house.jpg','Contemporary timber-clad house under open sky']] as const
const gallery = [['/images/living-greenery.jpg','Sunlit living room with indoor plants','Light & greenery','Residential study','md:col-span-2 md:row-span-2'],['/images/calm-corner.jpg','Quiet reading corner with a yellow armchair','A quiet corner','Interior study',''],['/images/villa-pool.jpg','White villa beside a turquoise pool','An open outlook','Exterior study',''],['/images/warm-lounge.jpg','Warm lounge with long windows and timber floors','Grounded warmth','Living space','md:col-span-2'],['/images/garden-house.jpg','Modern home glowing at dusk beneath a large tree','Open to the east','Architecture study','md:col-span-1']] as const

const contactPhone = process.env.NEXT_PUBLIC_CONTACT_PHONE?.trim()
const contactEmail = process.env.NEXT_PUBLIC_CONTACT_EMAIL?.trim()
const whatsappNumber = process.env.NEXT_PUBLIC_WHATSAPP_NUMBER?.replace(/\D/g, '')
export const contact = {
  phone: contactPhone,
  tel: contactPhone ? `tel:${contactPhone.replace(/[^+\d]/g, '')}` : undefined,
  email: contactEmail,
  whatsapp: whatsappNumber ? `https://wa.me/${whatsappNumber}` : undefined,
  location: 'Dubai, United Arab Emirates',
}

// Line-art emblem: an open ring holding a roofline with a K beneath it.
export function LogoMark({ className = 'size-11' }: { className?: string }) { return <svg viewBox="0 0 64 64" fill="none" stroke="currentColor" strokeWidth="2.4" strokeLinecap="square" className={className} aria-hidden><path d="M59.57 36.86A28 28 0 1 1 50 10.55" /><path d="M14 39 36 19.5 58 39" /><path d="M20.5 34v16M51.5 34v11" /><path d="M31 33v17M31 42l8-8M33.5 39.5 41 50" /></svg> }
export function Logo({ light = false }: { light?: boolean }) { return <Link href="/" className="flex items-center gap-3" aria-label="Kavach home"><LogoMark className={`size-11 ${light ? 'text-[#d9bf9a]' : 'text-[#a57a4a]'}`} /><span className="leading-none"><span className="block font-sans text-[1.05rem] font-medium tracking-[.42em]">KAVACH</span><span className={`mt-1.5 block text-[9px] tracking-[.38em] ${light ? 'text-white/60' : 'text-[#2a1b1f]/50'}`}>VASTU CONSULTANCY</span></span></Link> }

const Eyebrow = ({ children, light = false }: { children: React.ReactNode; light?: boolean }) => <p className={`flex items-center gap-4 text-[11px] uppercase tracking-[.28em] ${light ? 'text-[#d9bf9a]' : 'text-[#a57a4a]'}`}><span className="h-px w-10 bg-current" />{children}</p>
const btn = 'inline-flex items-center gap-3 px-7 py-4 text-[11px] font-medium uppercase tracking-[.22em] transition-colors'

export function Header({ overlay = false }: { overlay?: boolean }) {
  const [open, setOpen] = useState(false)
  return <header className={overlay ? 'absolute inset-x-0 top-0 z-30 border-b border-white/15' : 'border-b border-[#2a1b1f]/10 bg-[#f6f1ea]'}><div className={`mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-10 ${overlay ? 'text-white' : 'text-[#2a1b1f]'}`}><Logo light={overlay} /><nav className="hidden gap-9 text-[12px] uppercase tracking-[.18em] lg:flex" aria-label="Primary navigation">{nav.map(([label, href]) => <Link key={href} href={href} className="transition-opacity hover:opacity-60">{label}</Link>)}</nav><Link href="/bookings" className={`hidden lg:inline-flex ${btn} ${overlay ? 'border border-white/50 hover:bg-white hover:text-[#2a1b1f]' : 'bg-[#3b1220] text-[#f6f1ea] hover:bg-[#a57a4a]'}`}>Book a consultation</Link><button className="p-2 lg:hidden" onClick={() => setOpen(!open)} aria-label={open ? 'Close menu' : 'Open menu'}>{open ? <X /> : <Menu />}</button></div>{open && <nav className="flex flex-col divide-y divide-[#2a1b1f]/10 border-t border-[#2a1b1f]/10 bg-[#f6f1ea] px-5 text-[13px] uppercase tracking-[.18em] text-[#2a1b1f] lg:hidden">{nav.map(([label, href]) => <Link className="py-4" onClick={() => setOpen(false)} key={href} href={href}>{label}</Link>)}</nav>}</header>
}

// Footer doubles as a full contact transcript so details and every page are one tap away site-wide.
export function Footer() { const details = [[contact.phone ? 'Phone' : '', contact.phone, contact.tel, Phone], [contact.email ? 'Email' : '', contact.email, contactEmail ? `mailto:${contactEmail}` : undefined, Mail], [contact.whatsapp ? 'WhatsApp' : '', 'Message us', contact.whatsapp, MessageCircle]] as const; return <footer className="bg-[#3b1220] px-5 pb-10 pt-20 text-[#f6f1ea] lg:px-10"><div className="mx-auto max-w-7xl"><div className="grid gap-14 lg:grid-cols-[1.2fr_1fr_.7fr]"><div><Eyebrow light>Contact details</Eyebrow><h2 className="mt-6 font-serif text-5xl font-light leading-[1.05] sm:text-6xl">Let&apos;s talk about<br /><em className="text-[#d9bf9a]">your space.</em></h2><p className="mt-6 max-w-sm text-sm leading-7 text-white/60">Spatial advisory for more intentional living and working. Tell us what you are looking for and we will help you find the right next step.</p></div><dl className="divide-y divide-white/10 border-y border-white/10 text-sm">{details.filter(([label]) => label).map(([label,value,href,Icon]) => <div key={label} className="flex items-baseline justify-between gap-6 py-4"><dt className="text-[11px] uppercase tracking-[.22em] text-white/45">{label}</dt><dd>{href && value && <a href={href} {...(href.startsWith('http') ? {target:'_blank',rel:'noopener noreferrer'} : {})} className="break-all font-serif text-xl hover:text-[#d9bf9a]"><Icon className="mr-2 inline size-4 text-[#d9bf9a]" />{value}</a>}</dd></div>)}<div className="flex items-baseline justify-between gap-6 py-4"><dt className="text-[11px] uppercase tracking-[.22em] text-white/45">Studio</dt><dd className="text-right text-white/80"><MapPin className="mr-2 inline size-4 text-[#d9bf9a]" />{contact.location}</dd></div>{!contact.phone && !contact.email && !contact.whatsapp && <div className="py-4 text-white/70"><Link href="/bookings" className="underline underline-offset-4">Request a consultation</Link></div>}</dl><nav aria-label="Footer navigation"><p className="text-[11px] uppercase tracking-[.22em] text-white/45">Pages</p><ul className="mt-4 flex flex-col gap-3 font-serif text-xl">{nav.map(([label, href]) => <li key={href}><Link href={href} className="text-white/85 hover:text-[#d9bf9a]">{label}</Link></li>)}</ul></nav></div><div className="mt-20 flex flex-col items-start justify-between gap-6 border-t border-white/10 pt-8 sm:flex-row sm:items-center"><Logo light /><p className="text-xs text-white/40">© 2026 Kavach Consultancy, Dubai</p></div></div></footer> }

export function HomePage() { return <><Header overlay /><main>
  <section className="relative h-[100svh] min-h-[620px] overflow-hidden bg-[#9fb6cf]"><Image src="/images/hero-villa.jpg" alt="Light-filled modern villa with a reflecting pool under a clear sky" fill sizes="100vw" className="object-cover object-[center_70%]" priority /><div className="absolute inset-0 bg-gradient-to-b from-[#7f9cbb]/50 via-transparent to-[#1e0a11]/85" /><p aria-hidden className="pointer-events-none absolute inset-x-0 top-[14vh] select-none text-center font-sans text-[21vw] font-medium leading-none tracking-[.02em] lg:top-[12vh]"><span className="bg-gradient-to-b from-white via-white/85 to-white/0 bg-clip-text text-transparent">KAVACH</span></p><div className="absolute inset-x-0 bottom-0 z-10 mx-auto grid max-w-7xl gap-8 px-5 pb-12 text-white lg:grid-cols-[1.4fr_1fr] lg:items-end lg:px-10 lg:pb-16"><div><Eyebrow light>Spatial advisory rooted in Vastu</Eyebrow><h1 className="mt-5 font-serif text-5xl font-light leading-[.98] sm:text-7xl">Spaces that <em className="text-[#d9bf9a]">feel like home.</em></h1></div><div className="border-l border-white/25 pl-6"><p className="text-sm leading-6 text-white/90">Go beyond listings. See whether a home’s layout, orientation and flow fit your life—before you buy, rent or redesign.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/bookings" className={`${btn} bg-[#a57a4a] text-white hover:bg-[#8d6539]`}>Start a conversation <ArrowUpRight className="size-4" /></Link><Link href="/services" className={`${btn} border border-white/50 hover:bg-white hover:text-[#2a1b1f]`}>Our services</Link></div></div></div></section>
  <section className="mx-auto grid max-w-7xl gap-14 px-5 py-28 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:gap-24 lg:px-10"><div className="relative mx-auto w-full max-w-[460px]"><div className="relative aspect-[.8] overflow-hidden rounded-t-full"><Image src="/images/kavach-hero.png" alt="Sunlit interior with a rounded doorway and indoor greenery" fill sizes="(max-width: 1024px) 100vw, 460px" className="object-cover" /></div><p className="mt-4 text-[11px] uppercase tracking-[.22em] text-[#2a1b1f]/50">A considered approach to every space</p></div><div><Eyebrow>Our approach</Eyebrow><h2 className="mt-6 font-serif text-5xl font-light leading-[1.05] sm:text-6xl">Light, flow and orientation, <em className="text-[#a57a4a]">read with care.</em></h2><p className="mt-8 max-w-md leading-8 text-[#2a1b1f]/70">Founded by Vedang Joshi, Kavach looks at how a space is lived in: where the morning light lands, how people move, and what each room is asked to do. Recommendations are practical, considered, and shaped around your priorities.</p><Link href="/about" className="mt-8 inline-block text-[11px] uppercase tracking-[.22em] text-[#a57a4a] underline underline-offset-8">Meet your advisor</Link></div></section>
  <section className="bg-[#ebe3d8] px-5 py-28 lg:px-10"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-6 border-b border-[#2a1b1f]/15 pb-10 md:flex-row md:items-end"><div><Eyebrow>How we help</Eyebrow><h2 className="mt-6 font-serif text-5xl font-light sm:text-6xl">Advice for the spaces that matter.</h2></div><Link href="/services" className="text-[11px] uppercase tracking-[.22em] text-[#a57a4a] underline underline-offset-8">All services</Link></div><div className="mt-12 grid gap-10 md:grid-cols-3 md:gap-8">{services.map(([title, description, src, alt], i) => <Link href={`/services#${title.toLowerCase().replaceAll(' ','-')}`} key={title} className="group block"><div className="relative aspect-[4/5] overflow-hidden"><Image src={src} alt={alt} fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover transition-transform duration-[1.2s] group-hover:scale-[1.04]" /></div><div className="mt-6 flex gap-5"><span className="font-serif text-lg italic text-[#a57a4a]">0{i+1}</span><div><h3 className="font-serif text-3xl">{title}</h3><p className="mt-2 text-sm leading-6 text-[#2a1b1f]/65">{description}</p></div></div></Link>)}</div></div></section>
  <section className="mx-auto max-w-7xl px-5 py-28 lg:px-10"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><Eyebrow>Selected spaces</Eyebrow><h2 className="mt-6 font-serif text-5xl font-light sm:text-6xl">Calm, considered, <em className="text-[#a57a4a]">lived in.</em></h2></div><Link href="/blogs" className="text-[11px] uppercase tracking-[.22em] text-[#a57a4a] underline underline-offset-8">Read the journal</Link></div><div className="mt-14 grid auto-rows-[260px] gap-x-4 gap-y-12 md:grid-cols-4">{gallery.map(([src, alt, caption, place, span]) => <figure key={src} className={`group flex flex-col ${span}`}><div className="relative min-h-0 flex-1 overflow-hidden"><Image src={src} alt={alt} fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover transition-transform duration-[1.2s] group-hover:scale-[1.04]" /></div><figcaption className="mt-3 flex justify-between gap-4 text-xs"><span className="font-serif text-base italic">{caption}</span><span className="uppercase tracking-[.18em] text-[#2a1b1f]/45">{place}</span></figcaption></figure>)}</div></section>
  <section className="relative h-[80svh] min-h-[480px] overflow-hidden"><Image src="/images/dubai-skyline.jpg" alt="Dubai skyline at sunrise" fill sizes="100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#1e0a11]/90 via-[#1e0a11]/25 to-transparent" /><div className="absolute inset-x-0 bottom-0 mx-auto max-w-7xl px-5 pb-14 text-white lg:px-10"><Eyebrow light>Based in Dubai</Eyebrow><h2 className="mt-6 max-w-3xl font-serif text-5xl font-light leading-[1.02] sm:text-7xl">Ready when you are. <em className="text-[#d9bf9a]">Let&apos;s begin.</em></h2><div className="mt-9 flex flex-wrap gap-3"><Link href="/bookings" className={`${btn} bg-[#a57a4a] hover:bg-[#8d6539]`}>Book a consultation <ArrowUpRight className="size-4" /></Link><Link href="/contact" className={`${btn} border border-white/50 hover:bg-white hover:text-[#2a1b1f]`}>Contact us</Link></div></div></section>
</main><Footer /></> }

export function StandardPage({title, eyebrow, image, imageAlt, children}: {title:string; eyebrow:string; image?:string; imageAlt?:string; children:React.ReactNode}) { return <><Header /><main><div className="mx-auto max-w-7xl px-5 pt-20 lg:px-10 lg:pt-28"><Eyebrow>{eyebrow}</Eyebrow><h1 className="mt-6 max-w-4xl font-serif text-5xl font-light leading-[1.02] sm:text-8xl">{title}</h1></div>{image && <div className="relative mx-auto mt-16 h-[60svh] min-h-[320px] max-w-7xl sm:px-5 lg:px-10"><div className="relative h-full overflow-hidden"><Image src={image} alt={imageAlt ?? ''} fill sizes="100vw" className="object-cover" priority /></div></div>}<div className="mx-auto max-w-7xl px-5 py-20 lg:px-10 lg:py-28">{children}</div></main><Footer /></> }

const field = 'border-0 border-b border-[#2a1b1f]/25 bg-transparent px-0 py-3 text-base focus:border-[#a57a4a] focus:outline-none focus:ring-0'
const labelCls = 'flex flex-col gap-1 text-[11px] uppercase tracking-[.2em] text-[#2a1b1f]/60'
export function BookingForm() {
  const [status, setStatus] = useState('')
  const [pending, setPending] = useState(false)
  async function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault()
    const form = e.currentTarget
    setPending(true)
    setStatus('')
    try {
      const response = await fetch('/api/bookings', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(Object.fromEntries(new FormData(form))) })
      const result = await response.json()
      if (!response.ok) throw new Error(result.error || 'We could not send your request right now.')
      setStatus('Thank you. Your booking enquiry has been sent. We will be in touch soon.')
      form.reset()
    } catch (error) {
      setStatus(error instanceof Error ? error.message : 'We could not send your request right now. Please try again.')
    } finally {
      setPending(false)
    }
  }
  return <form onSubmit={submit} aria-busy={pending} className="grid max-w-3xl gap-x-10 gap-y-8 border border-[#2a1b1f]/10 bg-[#fbf8f3] p-6 sm:grid-cols-2 sm:p-12">
    <label className={labelCls}>Your name<input required maxLength={120} name="name" autoComplete="name" className={`${field} normal-case tracking-normal text-[#2a1b1f]`} /></label>
    <label className={labelCls}>Email address<input required maxLength={254} name="email" type="email" autoComplete="email" className={`${field} normal-case tracking-normal text-[#2a1b1f]`} /></label>
    <label className={labelCls}>Phone number<input required maxLength={40} name="phone" type="tel" autoComplete="tel" className={`${field} normal-case tracking-normal text-[#2a1b1f]`} /></label>
    <label className={labelCls}>Preferred date<input required name="date" type="date" className={`${field} normal-case tracking-normal text-[#2a1b1f]`} /></label>
    <label className={`${labelCls} sm:col-span-2`}>Property type<select required name="propertyType" className={`${field} normal-case tracking-normal text-[#2a1b1f]`}><option value="">Select one</option><option>Home</option><option>Workplace</option><option>Development</option></select></label>
    <label className={`${labelCls} sm:col-span-2`}>How can we help?<textarea required maxLength={5000} name="message" rows={4} className={`${field} normal-case tracking-normal text-[#2a1b1f]`} /></label>
    <div className="sm:col-span-2"><button disabled={pending} className={`${btn} bg-[#3b1220] text-[#f6f1ea] hover:bg-[#a57a4a] disabled:cursor-wait disabled:opacity-60`}>{pending ? 'Sending…' : 'Submit booking enquiry'} <ArrowUpRight className="size-4" /></button>{status && <p role={status.startsWith('Thank you') ? 'status' : 'alert'} className="mt-4 text-sm text-[#2a1b1f]">{status}</p>}</div>
  </form>
}

export { Phone, Sparkles }

export const ServiceCards = () => <div className="divide-y divide-[#2a1b1f]/15 border-y border-[#2a1b1f]/15">{services.map(([title, description, src, alt], i) => { const href = i === 0 ? '/services/residential' : i === 1 ? '/services/workplace' : '/services/development'; return <article id={title.toLowerCase().replaceAll(' ','-')} key={title} className="grid gap-8 py-12 md:grid-cols-[auto_1fr_1fr] md:items-center md:gap-14"><span className="font-serif text-5xl italic text-[#a57a4a]">0{i+1}</span><div><h2 className="font-serif text-4xl">{title}</h2><p className="mt-4 max-w-md leading-7 text-[#2a1b1f]/70">{description}</p><Link href={href} className="mt-8 inline-block text-[11px] uppercase tracking-[.22em] text-[#a57a4a] underline underline-offset-8">Explore this service</Link><br /><Link href="/bookings" className="mt-4 inline-block text-[11px] uppercase tracking-[.22em] text-[#a57a4a] underline underline-offset-8">Arrange a consultation</Link></div><div className="relative aspect-[4/3] overflow-hidden"><Image src={src} alt={alt} fill sizes="(max-width: 768px) 100vw, 40vw" className="object-cover" /></div></article> })}</div>

export const Booking = () => <StandardPage eyebrow="Your next step" title="Let&apos;s make space for good." image="/images/warm-lounge.jpg" imageAlt="Warm lounge with long windows and timber floors"><p className="mb-12 max-w-xl leading-8 text-[#2a1b1f]/70">Tell us a little about your space and preferred timing. The team can then follow up with next steps. For direct enquiries, visit our <Link href="/contact" className="underline underline-offset-4">contact page</Link>.</p><BookingForm /></StandardPage>
export const Contact = () => {
  const options: Array<[LucideIcon, string, string, string]> = []
  if (contact.phone && contact.tel) options.push([Phone, 'Call us', contact.phone, contact.tel])
  if (contact.email) options.push([Mail, 'Email us', contact.email, `mailto:${contact.email}`])
  if (contact.whatsapp) options.push([MessageCircle, 'WhatsApp', 'Message us directly', contact.whatsapp])
  return <StandardPage eyebrow="Get in touch" title="A thoughtful conversation starts here." image="/images/garden-house.jpg" imageAlt="Modern home glowing at dusk beneath a large tree"><div className="grid border-y border-[#2a1b1f]/15 md:grid-cols-3 md:divide-x md:divide-[#2a1b1f]/15">{options.map(([Icon,label,value,href]) => <a key={label} href={href} {...(href.startsWith('http') ? {target:'_blank',rel:'noopener noreferrer'} : {})} className="group flex min-h-[220px] flex-col justify-between border-b border-[#2a1b1f]/15 py-8 transition-colors last:border-b-0 hover:bg-[#ebe3d8] md:border-b-0 md:px-8"><Icon className="size-6 text-[#a57a4a]" /><div><p className="text-[11px] uppercase tracking-[.22em] text-[#2a1b1f]/50">{label}</p><p className="mt-3 break-all font-serif text-3xl">{value}</p></div></a>)}</div>{options.length === 0 && <div className="py-12"><p className="max-w-xl leading-7 text-[#2a1b1f]/70">Share a few details about your space and we can arrange a conversation.</p><Link href="/bookings" className={`${btn} mt-6 bg-[#3b1220] text-[#f6f1ea] hover:bg-[#a57a4a]`}>Request a consultation <ArrowUpRight className="size-4" /></Link></div>}<p className="mt-8 text-sm text-[#2a1b1f]/60"><MapPin className="mr-2 inline size-4 text-[#a57a4a]" />{contact.location}</p></StandardPage>
}
export const Blogs = () => <StandardPage eyebrow="From the journal" title="A little perspective." image="/images/calm-corner.jpg" imageAlt="Quiet reading corner with a yellow armchair"><div className="grid gap-12 md:grid-cols-3 md:gap-8">{[['What Vastu is, and what it is not','A grounded introduction to Vastu, separating practical spatial guidance from superstition and rigid rules.','/images/living-greenery.jpg','5 min read'],['Choosing a home that feels right','A simple lens for noticing light, flow, orientation, and the everyday feeling of a potential home.','/images/villa-pool.jpg','4 min read'],['The quiet power of a well-oriented workplace','How thoughtful planning can support focus, collaboration, and a calmer rhythm at work.','/images/workplace.jpg','6 min read']].map(([title, preview, src, length],i)=><article key={title} tabIndex={0} aria-describedby={`article-preview-${i}`} className="group relative cursor-help outline-none focus-visible:ring-2 focus-visible:ring-[#a57a4a] focus-visible:ring-offset-4"><div className="relative aspect-[4/5] overflow-hidden"><Image src={src} alt="" fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover transition-transform duration-[1.2s] group-hover:scale-[1.04]" /><div id={`article-preview-${i}`} role="tooltip" className="pointer-events-none absolute inset-0 z-20 flex items-end bg-[#3b1220]/90 p-7 text-sm leading-7 text-[#f6f1ea] opacity-0 transition-opacity duration-500 group-hover:opacity-100 group-focus:opacity-100"><div><span className="mb-3 block text-[11px] uppercase tracking-[.22em] text-[#d9bf9a]">Article preview</span><p>{preview}</p></div></div></div><p className="mt-5 text-[11px] uppercase tracking-[.22em] text-[#2a1b1f]/45">Essay · {length}</p><h2 className="mt-2 font-serif text-3xl leading-tight">{title}</h2></article>)}</div></StandardPage>
export const About = () => <StandardPage eyebrow="A different way to look at space" title="Ancient wisdom. Clear-eyed advice." image="/images/dubai-skyline.jpg" imageAlt="Dubai skyline at sunrise"><div className="grid gap-16 lg:grid-cols-[1.2fr_1fr] lg:items-center"><div className="max-w-2xl"><p className="font-serif text-3xl font-light leading-snug text-[#2a1b1f]/90">Vastu is not about fear or rigid rules. It is a thoughtful way to understand how light, movement, orientation and intention shape the way a space feels.</p><p className="mt-8 leading-8 text-[#2a1b1f]/65">Founded by Vedang Joshi, Kavach offers practical, considered recommendations for the way people live and work today. We begin by listening to what matters to you, then look at the space and its possibilities together.</p><Link href="/services" className="mt-8 inline-block text-[11px] uppercase tracking-[.22em] text-[#a57a4a] underline underline-offset-8">Explore our services</Link></div><div className="relative mx-auto aspect-[.8] w-full max-w-[420px] overflow-hidden rounded-t-full"><Image src="/images/kavach-hero.png" alt="Sunlit interior with a rounded doorway and indoor greenery" fill sizes="(max-width: 1024px) 100vw, 40vw" className="object-cover" /></div></div></StandardPage>
export const ServiceDetail = ({ title, eyebrow, image, imageAlt, intro, points }: { title:string; eyebrow:string; image:string; imageAlt:string; intro:string; points:string[] }) => <StandardPage eyebrow={eyebrow} title={title} image={image} imageAlt={imageAlt}><div className="grid gap-14 lg:grid-cols-[1.1fr_.9fr]"><div><p className="max-w-2xl font-serif text-3xl font-light leading-snug text-[#2a1b1f]/90">{intro}</p><Link href="/bookings" className={`${btn} mt-8 bg-[#3b1220] text-[#f6f1ea] hover:bg-[#a57a4a]`}>Arrange a consultation <ArrowUpRight className="size-4" /></Link></div><ul className="divide-y divide-[#2a1b1f]/15 border-y border-[#2a1b1f]/15">{points.map((point,index)=><li key={point} className="flex gap-6 py-5"><span className="font-serif text-xl italic text-[#a57a4a]">0{index+1}</span><span className="leading-7 text-[#2a1b1f]/70">{point}</span></li>)}</ul></div><div className="mt-20 border-t border-[#2a1b1f]/15 pt-8"><Link href="/services" className="text-[11px] uppercase tracking-[.22em] text-[#a57a4a] underline underline-offset-8">Back to all services</Link></div></StandardPage>
export const Services = () => <StandardPage eyebrow="How we help" title="Advice for the spaces that matter most." image="/images/bright-living.jpg" imageAlt="Bright open-plan living room with soft sofas"><ServiceCards /></StandardPage>
