'use client'

import Image from 'next/image'
import Link from 'next/link'
import { FormEvent, useState } from 'react'
import { ArrowUpRight, Compass, Mail, MapPin, Menu, MessageCircle, MoveRight, Phone, Sparkles, X } from 'lucide-react'

// Contact sits last so every navigation path ends with a way to reach us.
const nav = [['Home','/'],['About','/about'],['Services','/services'],['Journal','/blogs'],['Bookings','/bookings'],['Contact','/contact']] as const
const services = [['Home harmony','Guidance for buying, renting, or redesigning a home.','/images/bright-living.jpg','Bright open-plan living room with soft sofas'],['Workplace flow','Spatial advice for focus, culture, and better work.','/images/workplace.jpg','Calm modern office corridor with natural tones'],['Developer advisory','A considered perspective from concept through handover.','/images/timber-house.jpg','Contemporary timber-clad house under open sky']] as const
const gallery = [['/images/living-greenery.jpg','Sunlit living room with indoor plants','Light & greenery','md:col-span-2 md:row-span-2'],['/images/calm-corner.jpg','Quiet reading corner with a yellow armchair','A quiet corner',''],['/images/villa-pool.jpg','White villa beside a turquoise pool','Water in the north-east',''],['/images/warm-lounge.jpg','Warm lounge with long windows and timber floors','Grounded warmth','md:col-span-2'],['/images/garden-house.jpg','Modern home glowing at dusk beneath a large tree','Open to the east','md:col-span-1']] as const

export const contact = { phone: '+971 50 123 4567', tel: 'tel:+971501234567', email: 'hello@kavachconsultancy.com', whatsapp: 'https://wa.me/971501234567', location: 'Dubai, United Arab Emirates', hours: 'Sunday – Thursday · 9:00 – 18:00 GST' }

export function Header({ overlay = false }: { overlay?: boolean }) {
  const [open, setOpen] = useState(false)
  const tone = overlay ? 'text-white' : 'text-[#263c35]'
  return <header className={overlay ? 'absolute inset-x-0 top-0 z-30' : 'border-b border-[#263c35]/10 bg-[#fcfaf6]/90 backdrop-blur-md'}><div className={`mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-10 ${tone}`}><Link href="/" className="flex items-center gap-3" aria-label="Kavach home"><span className="grid size-10 place-items-center rounded-full bg-[#f4dfd3] text-[#a8553f]"><Compass className="size-5" /></span><span className="font-serif text-xl">Kavach<span className="text-[#a8553f]">.</span></span></Link><nav className="hidden gap-8 text-sm lg:flex" aria-label="Primary navigation">{nav.map(([label, href]) => <Link key={href} href={href} className="transition-opacity hover:opacity-70">{label}</Link>)}</nav><Link href="/bookings" className={`hidden rounded-full px-5 py-3 text-sm font-medium lg:block ${overlay ? 'bg-white/90 text-[#263c35] backdrop-blur' : 'bg-[#263c35] text-[#fcfaf6]'}`}>Book a consultation <ArrowUpRight className="ml-2 inline size-4" /></Link><button className={`rounded-full border p-2 lg:hidden ${overlay ? 'border-white/40' : 'border-[#263c35]/15'}`} onClick={() => setOpen(!open)} aria-label={open ? 'Close menu' : 'Open menu'}>{open ? <X /> : <Menu />}</button></div>{open && <nav className="flex flex-col gap-5 border-t border-[#263c35]/10 bg-[#fcfaf6] px-5 py-6 text-sm text-[#263c35] lg:hidden">{nav.map(([label, href]) => <Link onClick={() => setOpen(false)} key={href} href={href}>{label}</Link>)}</nav>}</header>
}

// Footer doubles as a full contact transcript so details and every page are one tap away site-wide.
export function Footer() { return <footer className="bg-[#263c35] px-5 pb-10 pt-20 text-[#fcfaf6] lg:px-10"><div className="mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-[1.2fr_1fr_.8fr]"><div><p className="text-xs uppercase tracking-[.2em] text-[#f4dfd3]/70">Contact details</p><h2 className="mt-4 font-serif text-4xl leading-tight sm:text-5xl">Let&apos;s talk about<br /><em className="text-[#f4dfd3]">your space.</em></h2><p className="mt-5 max-w-sm text-sm leading-6 text-white/60">Spatial advisory for more intentional living and working. Reach out directly — we usually reply within one working day.</p></div><dl className="flex flex-col gap-6 text-sm"><div><dt className="text-xs uppercase tracking-[.15em] text-white/45">Phone</dt><dd className="mt-1.5"><a href={contact.tel} className="text-lg hover:text-[#f4dfd3]"><Phone className="mr-2 inline size-4 text-[#f4dfd3]" />{contact.phone}</a></dd></div><div><dt className="text-xs uppercase tracking-[.15em] text-white/45">Email</dt><dd className="mt-1.5"><a href={`mailto:${contact.email}`} className="break-all text-lg hover:text-[#f4dfd3]"><Mail className="mr-2 inline size-4 text-[#f4dfd3]" />{contact.email}</a></dd></div><div><dt className="text-xs uppercase tracking-[.15em] text-white/45">WhatsApp</dt><dd className="mt-1.5"><a href={contact.whatsapp} target="_blank" rel="noopener noreferrer" className="text-lg hover:text-[#f4dfd3]"><MessageCircle className="mr-2 inline size-4 text-[#f4dfd3]" />Message us</a></dd></div><div><dt className="text-xs uppercase tracking-[.15em] text-white/45">Studio</dt><dd className="mt-1.5 text-white/80"><MapPin className="mr-2 inline size-4 text-[#f4dfd3]" />{contact.location}<br /><span className="ml-6 text-white/50">{contact.hours}</span></dd></div></dl><nav aria-label="Footer navigation"><p className="text-xs uppercase tracking-[.15em] text-white/45">Pages</p><ul className="mt-3 flex flex-col gap-2.5 text-sm">{nav.map(([label, href]) => <li key={href}><Link href={href} className="text-white/80 hover:text-[#f4dfd3]">{label} <ArrowUpRight className="inline size-3.5 opacity-50" /></Link></li>)}</ul></nav></div><p aria-hidden className="mt-16 select-none font-serif text-[22vw] leading-[.8] tracking-[-.06em] text-white/[.06] lg:text-[15rem]">Kavach.</p><div className="mt-6 flex flex-col justify-between gap-3 border-t border-white/10 pt-5 text-xs text-white/40 sm:flex-row"><p>© 2026 Kavach Consultancy · Dubai, UAE</p><p><a href={contact.tel} className="hover:text-white">{contact.phone}</a> · <a href={`mailto:${contact.email}`} className="hover:text-white">{contact.email}</a></p></div></div></footer> }

export function HomePage() { return <><Header overlay /><main>
  <section className="relative h-[100svh] min-h-[620px] overflow-hidden bg-[#9fb6cf]"><Image src="/images/hero-villa.jpg" alt="Light-filled modern villa with a reflecting pool under a clear sky" fill sizes="100vw" className="object-cover object-[center_70%]" priority /><div className="absolute inset-0 bg-gradient-to-b from-[#7f9cbb]/55 via-transparent to-[#1b2a25]/80" /><p aria-hidden className="pointer-events-none absolute inset-x-0 top-[13vh] select-none text-center font-sans text-[23vw] font-bold leading-none tracking-[-.07em] lg:top-[11vh]"><span className="bg-gradient-to-b from-white via-white/90 to-white/0 bg-clip-text text-transparent">KAVACH</span></p><div className="absolute inset-x-0 bottom-0 z-10 mx-auto flex max-w-7xl flex-col gap-8 px-5 pb-12 text-white lg:flex-row lg:items-end lg:justify-between lg:px-10 lg:pb-16"><div><p className="mb-4 text-xs font-medium uppercase tracking-[.2em] text-[#f4dfd3]">Spatial advisory, rooted in Vastu</p><h1 className="font-serif text-4xl leading-[1.02] tracking-[-.03em] sm:text-6xl">Spaces that<br /><em className="text-[#f4dfd3]">feel like home.</em></h1></div><div className="max-w-sm"><p className="leading-7 text-white/80">Modern Vastu advisory for homes, workplaces and developments across Dubai — practical, personal, and grounded in how you want to live.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/bookings" className="rounded-full bg-[#a8553f] px-6 py-3.5 text-sm font-medium text-white">Start a conversation <MoveRight className="ml-2 inline size-4" /></Link><Link href="/services" className="rounded-full border border-white/40 px-6 py-3.5 text-sm font-medium backdrop-blur-sm">Explore services</Link></div></div></div></section>
  <section className="mx-auto grid max-w-7xl gap-14 px-5 py-24 lg:grid-cols-2 lg:items-center lg:px-10"><div className="relative mx-auto w-full max-w-[520px]"><div className="relative aspect-[.87] overflow-hidden rounded-[13rem] rounded-br-[3rem] rounded-tl-[3rem] bg-[#dfe9df]"><Image src="/images/kavach-hero.png" alt="Sunlit interior with a rounded doorway and indoor greenery" fill sizes="(max-width: 1024px) 100vw, 520px" className="object-cover" /></div></div><div><p className="text-xs uppercase tracking-[.2em] text-[#a8553f]">Our approach</p><h2 className="mt-4 font-serif text-4xl leading-tight sm:text-5xl">Light, flow and orientation — <em className="text-[#a8553f]">read with care.</em></h2><p className="mt-6 max-w-md leading-7 text-[#263c35]/70">We look at how a space is lived in: where the morning light lands, how people move, and what each room is asked to do. Then we offer clear, workable recommendations.</p><Link href="/about" className="mt-8 inline-block border-b border-[#a8553f] pb-1 text-sm font-medium text-[#a8553f]">More about Kavach <ArrowUpRight className="ml-1 inline size-4" /></Link></div></section>
  <section className="bg-[#dfe9df] px-5 py-24 lg:px-10"><div className="mx-auto max-w-7xl"><p className="text-xs uppercase tracking-[.2em] text-[#a8553f]">How we help</p><h2 className="mt-4 font-serif text-4xl sm:text-5xl">Advice for spaces that matter most.</h2><div className="mt-12 grid gap-5 md:grid-cols-3">{services.map(([title, description, src, alt], i) => <Link href={`/services#${title.toLowerCase().replaceAll(' ','-')}`} key={title} className="group overflow-hidden rounded-[2rem] bg-[#fcfaf6]"><div className="relative aspect-[4/3] overflow-hidden"><Image src={src} alt={alt} fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover transition-transform duration-700 group-hover:scale-105" /></div><div className="p-7"><span className="text-sm text-[#263c35]/50">0{i+1}</span><h3 className="mt-2 font-serif text-3xl">{title}</h3><p className="mt-3 text-sm leading-6 text-[#263c35]/70">{description}</p></div></Link>)}</div></div></section>
  <section className="mx-auto max-w-7xl px-5 py-24 lg:px-10"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs uppercase tracking-[.2em] text-[#a8553f]">Spaces we love</p><h2 className="mt-4 font-serif text-4xl sm:text-5xl">Calm, considered, lived in.</h2></div><Link href="/blogs" className="text-sm font-medium text-[#a8553f]">Read the journal <ArrowUpRight className="ml-1 inline size-4" /></Link></div><div className="mt-12 grid auto-rows-[240px] gap-4 md:grid-cols-4">{gallery.map(([src, alt, caption, span]) => <figure key={src} className={`group relative overflow-hidden rounded-[1.75rem] ${span}`}><Image src={src} alt={alt} fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover transition-transform duration-700 group-hover:scale-105" /><figcaption className="absolute bottom-4 left-4 rounded-full bg-[#fcfaf6]/90 px-4 py-2 text-xs font-medium backdrop-blur">{caption}</figcaption></figure>)}</div></section>
  <section className="relative h-[80svh] min-h-[480px] overflow-hidden"><Image src="/images/dubai-skyline.jpg" alt="Dubai skyline at sunrise" fill sizes="100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#1b2a25]/85 via-[#1b2a25]/20 to-transparent" /><div className="absolute inset-x-0 bottom-0 mx-auto max-w-7xl px-5 pb-14 text-white lg:px-10"><p className="text-xs uppercase tracking-[.2em] text-[#f4dfd3]">Based in Dubai</p><h2 className="mt-4 max-w-2xl font-serif text-4xl leading-tight sm:text-6xl">Ready when you are. <em className="text-[#f4dfd3]">Let&apos;s begin.</em></h2><div className="mt-8 flex flex-wrap gap-3"><Link href="/bookings" className="rounded-full bg-[#a8553f] px-6 py-3.5 text-sm font-medium">Book a consultation <MoveRight className="ml-2 inline size-4" /></Link><Link href="/contact" className="rounded-full border border-white/40 px-6 py-3.5 text-sm font-medium backdrop-blur-sm">Contact us</Link></div></div></section>
</main><Footer /></> }

export function StandardPage({title, eyebrow, image, imageAlt, children}: {title:string; eyebrow:string; image?:string; imageAlt?:string; children:React.ReactNode}) { return <><Header /><main><div className="mx-auto max-w-7xl px-5 pt-20 lg:px-10 lg:pt-28"><p className="text-xs uppercase tracking-[.2em] text-[#a8553f]">{eyebrow}</p><h1 className="mt-5 max-w-3xl font-serif text-5xl leading-tight sm:text-7xl">{title}</h1></div>{image && <div className="relative mx-auto mt-14 h-[55svh] min-h-[320px] max-w-[96rem] overflow-hidden sm:px-5 lg:px-10"><div className="relative h-full overflow-hidden sm:rounded-[2.5rem]"><Image src={image} alt={imageAlt ?? ''} fill sizes="100vw" className="object-cover" priority /></div></div>}<div className="mx-auto max-w-7xl px-5 py-16 lg:px-10 lg:py-24">{children}</div></main><Footer /></> }

export function BookingForm() { const [status, setStatus] = useState(''); async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = e.currentTarget; const res = await fetch('/api/bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(form)))}); setStatus(res.ok ? 'Thanks — your booking enquiry has been received.' : 'Something went wrong. Please try again.'); if(res.ok) form.reset() } return <form onSubmit={submit} className="flex max-w-2xl flex-col gap-5 rounded-[2rem] bg-[#f3eee6] p-6 sm:p-10"><label className="flex flex-col gap-2 text-sm">Your name<input required name="name" className="rounded-xl border border-[#263c35]/15 bg-[#fcfaf6] px-4 py-3" /></label><label className="flex flex-col gap-2 text-sm">Email address<input required name="email" type="email" className="rounded-xl border border-[#263c35]/15 bg-[#fcfaf6] px-4 py-3" /></label><label className="flex flex-col gap-2 text-sm">Phone number<input required name="phone" type="tel" className="rounded-xl border border-[#263c35]/15 bg-[#fcfaf6] px-4 py-3" /></label><label className="flex flex-col gap-2 text-sm">Preferred date<input required name="date" type="date" className="rounded-xl border border-[#263c35]/15 bg-[#fcfaf6] px-4 py-3" /></label><label className="flex flex-col gap-2 text-sm">Property type<select required name="propertyType" className="rounded-xl border border-[#263c35]/15 bg-[#fcfaf6] px-4 py-3"><option value="">Select one</option><option>Home</option><option>Workplace</option><option>Development</option></select></label><label className="flex flex-col gap-2 text-sm">How can we help?<textarea required name="message" rows={5} className="rounded-xl border border-[#263c35]/15 bg-[#fcfaf6] px-4 py-3" /></label><button className="rounded-full bg-[#a8553f] px-6 py-3.5 text-sm font-medium text-white">Submit booking enquiry <ArrowUpRight className="ml-2 inline size-4" /></button>{status && <p role="status" className="text-sm text-[#263c35]">{status}</p>}</form> }

export { Phone, Sparkles }

export const ServiceCards = () => <div className="grid gap-5 md:grid-cols-3">{services.map(([title, description, src, alt], i) => <article id={title.toLowerCase().replaceAll(' ','-')} key={title} className={`overflow-hidden rounded-[2rem] ${i===1?'bg-[#f4dfd3]':i===2?'bg-[#eee4cf]':'bg-[#e8f0e7]'}`}><div className="relative aspect-[4/3]"><Image src={src} alt={alt} fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover" /></div><div className="p-7"><h2 className="font-serif text-3xl">{title}</h2><p className="mt-4 leading-7 text-[#263c35]/70">{description}</p><Link href="/bookings" className="mt-8 block text-sm text-[#a8553f]">Tailored consultation →</Link></div></article>)}</div>

export const Booking = () => <StandardPage eyebrow="Your next step" title="Let&apos;s make space for good." image="/images/warm-lounge.jpg" imageAlt="Warm lounge with long windows and timber floors"><p className="mb-10 max-w-xl leading-7 text-[#263c35]/70">Tell us a little about your space and preferred timing. We will review your enquiry and respond with next steps.</p><BookingForm /></StandardPage>
export const Contact = () => <StandardPage eyebrow="Get in touch" title="A thoughtful conversation starts here." image="/images/garden-house.jpg" imageAlt="Modern home glowing at dusk beneath a large tree"><div className="grid gap-4 md:grid-cols-3">{([[Phone,'Call us',contact.phone,contact.tel],[Mail,'Email us',contact.email,`mailto:${contact.email}`],[MessageCircle,'WhatsApp','Message us directly',contact.whatsapp]] as const).map(([Icon,label,value,href]) => <a key={label} href={href} {...(href.startsWith('http') ? {target:'_blank',rel:'noopener noreferrer'} : {})} className="group flex min-h-[200px] flex-col justify-between rounded-[2rem] bg-[#f3eee6] p-7 transition-colors hover:bg-[#f4dfd3]"><Icon className="size-6 text-[#a8553f]" /><div><p className="text-xs uppercase tracking-[.15em] text-[#263c35]/50">{label}</p><p className="mt-2 break-all font-serif text-2xl">{value}</p></div></a>)}</div><p className="mt-8 text-sm text-[#263c35]/60"><MapPin className="mr-2 inline size-4 text-[#a8553f]" />{contact.location} · {contact.hours}</p></StandardPage>
export const Blogs = () => <StandardPage eyebrow="From the journal" title="A little perspective." image="/images/calm-corner.jpg" imageAlt="Quiet reading corner with a yellow armchair"><div className="grid gap-4 md:grid-cols-3">{[['What Vastu is — and what it is not','A grounded introduction to Vastu, separating practical spatial guidance from superstition and rigid rules.','/images/living-greenery.jpg'],['Choosing a home that feels right','A simple lens for noticing light, flow, orientation, and the everyday feeling of a potential home.','/images/villa-pool.jpg'],['The quiet power of a well-oriented workplace','How thoughtful planning can support focus, collaboration, and a calmer rhythm at work.','/images/workplace.jpg']].map(([title, preview, src],i)=><article key={title} tabIndex={0} aria-describedby={`article-preview-${i}`} className="group relative cursor-help overflow-hidden rounded-[1.5rem] bg-[#f4dfd3] outline-none transition-all duration-300 hover:-translate-y-1 hover:shadow-[0_18px_45px_rgba(38,60,53,.16)] focus-visible:ring-2 focus-visible:ring-[#a8553f] focus-visible:ring-offset-4"><div className="relative aspect-[16/10]"><Image src={src} alt="" fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover" /></div><div className="p-7"><h2 className="font-serif text-2xl">{title}</h2><p className="mt-6 text-sm leading-6 text-[#263c35]/70">Practical notes for creating spaces that support the way you live and work.</p></div><div id={`article-preview-${i}`} role="tooltip" className="pointer-events-none absolute inset-3 z-20 flex translate-y-2 items-center rounded-[1.25rem] bg-[#263c35] p-6 text-sm leading-6 text-[#fcfaf6] opacity-0 shadow-[0_18px_45px_rgba(38,60,53,.25)] transition-all duration-300 group-hover:translate-y-0 group-hover:opacity-100 group-focus:translate-y-0 group-focus:opacity-100"><div><span className="mb-3 block text-xs font-medium uppercase tracking-[.15em] text-[#f4dfd3]">Article preview</span><p>{preview}</p><span className="mt-4 block text-xs text-[#f4dfd3]/70">Move away to close</span></div></div></article>)}</div></StandardPage>
export const About = () => <StandardPage eyebrow="A different way to look at space" title="Ancient wisdom. Clear-eyed advice." image="/images/dubai-skyline.jpg" imageAlt="Dubai skyline at sunrise"><div className="grid gap-14 lg:grid-cols-[1.2fr_1fr] lg:items-center"><div className="max-w-2xl text-xl leading-8 text-[#263c35]/80">Vastu is not about fear or rigid rules. It is a thoughtful way to understand how light, movement, orientation and intention shape the way a space feels.<p className="mt-6 text-base leading-7 text-[#263c35]/65">Every recommendation is practical, considered, and tailored to the way you and your people actually live.</p></div><div className="relative aspect-[.87] overflow-hidden rounded-[13rem] rounded-br-[3rem] rounded-tl-[3rem]"><Image src="/images/kavach-hero.png" alt="Sunlit interior with a rounded doorway and indoor greenery" fill sizes="(max-width: 1024px) 100vw, 40vw" className="object-cover" /></div></div></StandardPage>
export const Services = () => <StandardPage eyebrow="How we help" title="Advice for the spaces that matter most." image="/images/bright-living.jpg" imageAlt="Bright open-plan living room with soft sofas"><ServiceCards /></StandardPage>
